### ISSUE TITLE
PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE

### ISSUE THREAD

**Issue by entaylor** [pmelchior/scarlet#199]
Hi hi –

I'm having an issue installing scarlet (Mac OS X 10.15.5).

I'm working in a virtual env, in which:
```
Python 3.6.11 (default, Jun 29 2020, 13:22:29)
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.62)] on darwin
```
and then:
```
>>> import numpy ; print( numpy.__version__ )
1.19.1
>>> import scipy ; print( scipy.__version__)
1.5.2
>>> import astropy ; print( astropy.__version__ )
4.1rc1
>>> import pybind11 ; print( pybind11.__version__ )
2.5.0
```
I can import all of proxmin, peigen, and autograd, but they have no __version__ methods.  But they have just been installed via pip, along with the other packages above.  So far so good.

But then:
```
>>> import scarlet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ent/work/hemisphot/scarlet/scarlet/__init__.py", line 6, in <module>
    from .source import *
  File "/Users/ent/work/hemisphot/scarlet/scarlet/source.py", line 3, in <module>
    from .initialization import *
  File "/Users/ent/work/hemisphot/scarlet/scarlet/initialization.py", line 3, in <module>
    from .observation import Observation, LowResObservation
  File "/Users/ent/work/hemisphot/scarlet/scarlet/observation.py", line 11, in <module>
    from scarlet.operators_pybind11 import apply_filter
ModuleNotFoundError: No module named 'scarlet.operators_pybind11'

```

When i look back at the install logs the only thing even vaguely suspicious is this:
```
creating build/temp.macosx-10.15-x86_64-3.6/scarlet
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Users/ent/work/hemisphot/venv/lib/python3.6/site-packages/pybind11/include -I/Users/ent/work/hemisphot/venv/lib/python3.6/site-packages/pybind11/include -I/Users/ent/work/hemisphot/venv/lib/python3.6/site-packages/peigen/include -I/Users/ent/work/hemisphot/venv/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c scarlet/operators_pybind11.cc -o build/temp.macosx-10.15-x86_64-3.6/scarlet/operators_pybind11.o -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="1.0" -std=c++14 -fvisibility=hidden
scarlet/operators_pybind11.cc:55:1: warning: 'pybind11_init' is deprecated:
      PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE
      [-Wdeprecated-declarations]
PYBIND11_PLUGIN(operators_pybind11)
^
/Users/ent/work/hemisphot/venv/lib/python3.6/site-packages/pybind11/include/pybind11/detail/common.h:271:20: note:
      expanded from macro 'PYBIND11_PLUGIN'
            return pybind11_init();                                            \
                   ^
scarlet/operators_pybind11.cc:55:1: note: 'pybind11_init' has been explicitly
      marked deprecated here
/Users/ent/work/hemisphot/venv/lib/python3.6/site-packages/pybind11/include/pybind11/detail/common.h:265:5: note:
      expanded from macro 'PYBIND11_PLUGIN'
    PYBIND11_DEPRECATED("PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE")  \
    ^
/Users/ent/work/hemisphot/venv/lib/python3.6/site-packages/pybind11/include/pybind11/detail/common.h:90:41: note:
      expanded from macro 'PYBIND11_DEPRECATED'
#  define PYBIND11_DEPRECATED(reason) [[deprecated(reason)]]
                                        ^
1 warning generated.
```
which may or may not be related.

Is there an immediately obvious explanation for what may have gone wrong here?   Is it a versioning issue?  Or is it just me?  : /

Thanks!

**Comment by fred3m** [comment]
You probably aren't picking up the installed version of scarlet. See #190 .

**Comment by entaylor** [comment]
Yes, it was the identical issue: simply that i hadn't cd..d from the directory where i'd installed scarlet.  That is embarrassing!  I'm not sure whether it's better or worse that i'm not the only one!

I wonder whether it's worth considering adding a line or a note to the installation to help avoid this?  I recognise it's a pretty silly mistake, but i suppose people do tend to switch off a bit when following step-by-step instructions.

**Comment by fred3m** [comment]
No problem, I'm glad that solved the issue. Closing this ticket.
