### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by cristobal-sifon** [pmelchior/scarlet#280]
Trying to install following the instructions I'm seeing the following error:
```
$ pip install .
Processing /home/cristobal/Documents/git/scarlet
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/cristobal/Documents/git/scarlet/setup.py", line 151, in <module>
          pkg_version = version.get_version()
                        ^^^^^^^^^^^^^^^^^^^^^
        File "/home/cristobal/Documents/git/scarlet/version.py", line 57, in get_version
          raise Exception("Could not find a public version of scarlet in the repo")
      Exception: Could not find a public version of scarlet in the repo
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Same happens when I execute `python setup.py install` instead. I found a similar (?) issue in #237 but I checked both my git (v2.40.1) and pip (23.2.1) are up to date. I tried this, with the same results, with Python 3.7, 3.9, and 3.11.

**Comment by fred3m** [comment]
What system are you using? I just tested isntalltion from scratch in an empty environment, on a macbook pro running OS X Ventura (13.4.1), and it built just fine.

**Comment by cristobal-sifon** [comment]
huh. I'm using Fedora 36 (thanks for the quick reply!)

**Comment by cristobal-sifon** [comment]
thanks! That did the trick

**Comment by fred3m** [comment]
Great!
